### ISSUE TITLE
Is this limited to iOS?

### ISSUE THREAD

**Issue by SteveDCronin** [forcedotcom/SalesforceMobileSDK-iOS-Distribution#71]
I'm wondering if there is something here that prevents this SDK from being used in a native Cocoa desktop application?

**Comment by khawkins** [comment]
There is UIKit-specific code scattered throughout the SDK, so it would need some work to be agnostic for both iOS and OS X.  Feel free to reach out on our [Google Plus Community](http://sfdc.co/mobilesdkcommunity) if you would like to discuss it further.
