### ISSUE TITLE
Settings.bundle overrides application one

### ISSUE THREAD

**Issue by dcacenabes** [forcedotcom/SalesforceMobileSDK-iOS-Distribution#75]
Hi,

We're using salesforce mobile SDK using Cocoapods. Our application uses the Settings.bundle and Root.plist files to display some settings in iOS settings app. It is being overridden by the Salesforce one, and our options are not displaying.

**Comment by khawkins** [comment]
@dcacenabes Could you re-open this Issue on [the main iOS repo](https://github.com/forcedotcom/SalesforceMobileSDK-iOS)?  This repo is a satellite repo to the main one, and issues tend to slip through the cracks here.  Plus, it has no relation to our CocoaPods implementation. :)  Thanks!
